import { describe, it, expect } from 'vitest';
import { SERVICES_WITH_PATH_REDIRECT, allSupportedGoogleServices, buildRedirectRules } from '../redirect-rules.js';

// ============================================================
// Helpers
// ============================================================

function escapeUrl(url) {
  return url.replace(/\./g, '\\.');
}

// Build regex patterns matching those generated by buildRedirectRules
function allowRegex(serviceUrl) {
  return new RegExp(`^https?://${escapeUrl(serviceUrl)}/.*u/\\d+(/|$|\\?).*`);
}

function insertRegex(serviceUrl) {
  return new RegExp(`^https?://${escapeUrl(serviceUrl)}/.*`);
}

function authuserRegex(serviceUrl) {
  return new RegExp(`^https?://([^/]*\\.)?${escapeUrl(serviceUrl)}/.*`);
}

function gmailRegex() {
  return new RegExp(`^https?://(www\\.)?gmail\\.com.*`);
}

// Simulate Chrome's priority-based rule matching (highest priority wins)
function findMatchingRule(rules, url) {
  const matches = rules.filter(rule => {
    const regex = new RegExp(rule.condition.regexFilter);
    return regex.test(url);
  });
  if (matches.length === 0) return null;
  return matches.reduce((best, r) => r.priority > best.priority ? r : best);
}

// ============================================================
// Test 1: Regex pattern matching
// ============================================================

describe('Regex pattern matching', () => {
  describe('Allow rule (path-redirect services)', () => {
    const services = [
      'calendar.google.com',
      'mail.google.com',
      'docs.google.com',
      'drive.google.com',
      'meet.google.com',
      'gemini.google.com',
    ];

    for (const service of services) {
      const regex = allowRegex(service);

      it(`${service}: matches URL with /u/0/`, () => {
        expect(regex.test(`https://${service}/u/0/`)).toBe(true);
      });

      it(`${service}: matches URL with /u/1/`, () => {
        expect(regex.test(`https://${service}/u/1/`)).toBe(true);
      });

      it(`${service}: matches URL with /u/5/`, () => {
        expect(regex.test(`https://${service}/u/5/`)).toBe(true);
      });

      it(`${service}: matches deep path with /u/N/`, () => {
        expect(regex.test(`https://${service}/calendar/u/1/r`)).toBe(true);
        expect(regex.test(`https://${service}/mail/u/0/inbox`)).toBe(true);
      });

      it(`${service}: matches /u/N with query string`, () => {
        expect(regex.test(`https://${service}/u/1?tab=rm`)).toBe(true);
      });

      it(`${service}: matches /u/N at end of URL`, () => {
        expect(regex.test(`https://${service}/u/1`)).toBe(true);
      });

      it(`${service}: does NOT match URL without /u/N/`, () => {
        expect(regex.test(`https://${service}/`)).toBe(false);
        expect(regex.test(`https://${service}/calendar/r`)).toBe(false);
      });
    }
  });

  describe('Insert rule (path-redirect services)', () => {
    it('matches base URL', () => {
      expect(insertRegex('calendar.google.com').test('https://calendar.google.com/')).toBe(true);
    });

    it('matches URL with path', () => {
      expect(insertRegex('calendar.google.com').test('https://calendar.google.com/calendar/r')).toBe(true);
    });

    it('matches http', () => {
      expect(insertRegex('calendar.google.com').test('http://calendar.google.com/')).toBe(true);
    });

    it('does NOT match different subdomain', () => {
      expect(insertRegex('calendar.google.com').test('https://evil-calendar.google.com/')).toBe(false);
    });

    it('does NOT match different domain', () => {
      expect(insertRegex('calendar.google.com').test('https://calendar.google.evil.com/')).toBe(false);
    });
  });

  describe('Authuser rule (standard services)', () => {
    it('matches exact domain', () => {
      expect(authuserRegex('analytics.google.com').test('https://analytics.google.com/')).toBe(true);
    });

    it('matches subdomain', () => {
      expect(authuserRegex('analytics.google.com').test('https://www.analytics.google.com/')).toBe(true);
    });

    it('matches with path', () => {
      expect(authuserRegex('analytics.google.com').test('https://analytics.google.com/analytics/web/')).toBe(true);
    });
  });

  describe('Gmail.com redirect rule', () => {
    const regex = gmailRegex();

    it('matches gmail.com', () => {
      expect(regex.test('https://gmail.com')).toBe(true);
    });

    it('matches gmail.com/', () => {
      expect(regex.test('https://gmail.com/')).toBe(true);
    });

    it('matches www.gmail.com', () => {
      expect(regex.test('https://www.gmail.com')).toBe(true);
    });

    it('matches http://gmail.com', () => {
      expect(regex.test('http://gmail.com')).toBe(true);
    });

    it('does NOT match mail.google.com', () => {
      expect(regex.test('https://mail.google.com/mail/')).toBe(false);
    });

    it('does NOT match notgmail.com', () => {
      expect(regex.test('https://notgmail.com')).toBe(false);
    });
  });

  describe('Allow rule prevents redirect for manual account URLs', () => {
    it('calendar /u/0/ is allowed (not redirected)', () => {
      expect(allowRegex('calendar.google.com').test('https://calendar.google.com/calendar/u/0/r')).toBe(true);
    });

    it('calendar /u/1/ is allowed', () => {
      expect(allowRegex('calendar.google.com').test('https://calendar.google.com/calendar/u/1/r')).toBe(true);
    });

    it('mail /u/0/ is allowed', () => {
      expect(allowRegex('mail.google.com').test('https://mail.google.com/mail/u/0/')).toBe(true);
    });

    it('mail /u/2/ is allowed', () => {
      expect(allowRegex('mail.google.com').test('https://mail.google.com/mail/u/2/inbox')).toBe(true);
    });

    it('calendar without /u/N/ is NOT allowed (will be redirected)', () => {
      expect(allowRegex('calendar.google.com').test('https://calendar.google.com/calendar/r')).toBe(false);
    });

    it('mail without /u/N/ is NOT allowed (will be redirected)', () => {
      expect(allowRegex('mail.google.com').test('https://mail.google.com/mail/')).toBe(false);
    });
  });
});

// ============================================================
// Test 2: Rule generation (using actual buildRedirectRules)
// ============================================================

describe('Rule generation', () => {
  const config = {
    defaultAccount: 1,
    accounts: [
      { isLoggedIn: true },
      { isLoggedIn: true },
      { isLoggedIn: true },
    ],
  };

  const rules = buildRedirectRules(config);

  it('generates gmail.com redirect rule', () => {
    const gmailRule = rules.find(r => r.condition.regexFilter.includes('gmail'));
    expect(gmailRule).toBeDefined();
    expect(gmailRule.action.type).toBe('redirect');
    expect(gmailRule.action.redirect.url).toBe('https://mail.google.com/mail/?authuser=1');
  });

  it('generates allow + insert rules for each path-redirect service', () => {
    for (const serviceUrl of SERVICES_WITH_PATH_REDIRECT) {
      const escaped = escapeUrl(serviceUrl);
      const serviceRules = rules.filter(r => r.condition.regexFilter.includes(escaped));
      const allowRules = serviceRules.filter(r => r.action.type === 'allow');
      const redirectRules = serviceRules.filter(r => r.action.type === 'redirect');

      expect(allowRules.length, `${serviceUrl} should have allow rule`).toBeGreaterThanOrEqual(1);
      expect(redirectRules.length, `${serviceUrl} should have redirect rule`).toBeGreaterThanOrEqual(1);
      expect(allowRules[0].priority, `${serviceUrl} allow priority > redirect priority`).toBeGreaterThan(redirectRules[0].priority);
    }
  });

  it('generates authuser redirect for standard services (e.g. analytics)', () => {
    const analyticsRule = rules.find(r =>
      r.condition.regexFilter.includes('analytics') && r.action.type === 'redirect'
    );
    expect(analyticsRule).toBeDefined();
    expect(analyticsRule.action.redirect.transform.queryTransform.addOrReplaceParams[0].value).toBe('1');
  });

  it('does NOT generate rules when defaultAccount is 0', () => {
    const noRules = buildRedirectRules({ defaultAccount: 0, accounts: [{ isLoggedIn: true }] });
    expect(noRules.length).toBe(0);
  });

  it('does NOT generate rules when account is not logged in', () => {
    const noRules = buildRedirectRules({
      defaultAccount: 1,
      accounts: [{ isLoggedIn: true }, { isLoggedIn: false }],
    });
    expect(noRules.length).toBe(0);
  });

  it('uses custom rule account for specific service', () => {
    const customRules = buildRedirectRules({
      defaultAccount: 1,
      customRules: [{ serviceName: 'Calendar', accountId: 2 }],
      accounts: [
        { isLoggedIn: true },
        { isLoggedIn: true },
        { isLoggedIn: true },
      ],
    });
    const calendarRedirect = customRules.find(r =>
      r.condition.regexFilter.includes('calendar') && r.action.type === 'redirect'
    );
    expect(calendarRedirect.action.redirect.transform.queryTransform.addOrReplaceParams[0].value).toBe('2');
  });

  it('generates rules for all path-redirect services from SERVICES_WITH_PATH_REDIRECT', () => {
    for (const serviceUrl of SERVICES_WITH_PATH_REDIRECT) {
      const service = allSupportedGoogleServices().find(s => s.url === serviceUrl);
      expect(service, `${serviceUrl} must exist in allSupportedGoogleServices()`).toBeDefined();
    }
  });

  it('includes excludedInitiatorDomains on redirect rules', () => {
    const redirectRules = rules.filter(r => r.action.type === 'redirect' && r.condition.excludedInitiatorDomains);
    expect(redirectRules.length).toBeGreaterThan(0);
    for (const rule of redirectRules) {
      expect(rule.condition.excludedInitiatorDomains).toContain('google.com');
      expect(rule.condition.excludedInitiatorDomains.length).toBeGreaterThan(100);
    }
  });
});

// ============================================================
// Test 3: Priority resolution
// ============================================================

describe('Rule priority resolution', () => {
  const rules = buildRedirectRules({
    defaultAccount: 1,
    accounts: [{ isLoggedIn: true }, { isLoggedIn: true }],
  });

  describe('Calendar', () => {
    it('calendar.google.com/ → redirect (add ?authuser=1)', () => {
      const match = findMatchingRule(rules, 'https://calendar.google.com/');
      expect(match.action.type).toBe('redirect');
    });

    it('calendar.google.com/calendar/u/0/r → allow (do not redirect)', () => {
      const match = findMatchingRule(rules, 'https://calendar.google.com/calendar/u/0/r');
      expect(match.action.type).toBe('allow');
    });

    it('calendar.google.com/calendar/u/1/r → allow (do not redirect)', () => {
      const match = findMatchingRule(rules, 'https://calendar.google.com/calendar/u/1/r');
      expect(match.action.type).toBe('allow');
    });
  });

  describe('Gmail / Mail', () => {
    it('gmail.com → redirect to mail.google.com with authuser', () => {
      const match = findMatchingRule(rules, 'https://gmail.com');
      expect(match.action.type).toBe('redirect');
      expect(match.action.redirect.url).toBe('https://mail.google.com/mail/?authuser=1');
    });

    it('www.gmail.com → redirect to mail.google.com with authuser', () => {
      const match = findMatchingRule(rules, 'https://www.gmail.com');
      expect(match.action.type).toBe('redirect');
      expect(match.action.redirect.url).toBe('https://mail.google.com/mail/?authuser=1');
    });

    it('mail.google.com/mail/ → redirect (add ?authuser=1)', () => {
      const match = findMatchingRule(rules, 'https://mail.google.com/mail/');
      expect(match.action.type).toBe('redirect');
    });

    it('mail.google.com/mail/u/0/ → allow (do not redirect)', () => {
      const match = findMatchingRule(rules, 'https://mail.google.com/mail/u/0/');
      expect(match.action.type).toBe('allow');
    });

    it('mail.google.com/mail/u/1/ → allow (do not redirect)', () => {
      const match = findMatchingRule(rules, 'https://mail.google.com/mail/u/1/');
      expect(match.action.type).toBe('allow');
    });
  });

  describe('Docs', () => {
    it('docs.google.com/ → redirect', () => {
      const match = findMatchingRule(rules, 'https://docs.google.com/');
      expect(match.action.type).toBe('redirect');
    });

    it('docs.google.com/document/u/0/d/xxx → allow', () => {
      const match = findMatchingRule(rules, 'https://docs.google.com/document/u/0/d/abc123');
      expect(match.action.type).toBe('allow');
    });
  });

  describe('Standard services (authuser)', () => {
    it('analytics.google.com/ → redirect', () => {
      const match = findMatchingRule(rules, 'https://analytics.google.com/');
      expect(match.action.type).toBe('redirect');
    });

    it('maps.google.com/maps → redirect', () => {
      const match = findMatchingRule(rules, 'https://maps.google.com/maps');
      expect(match.action.type).toBe('redirect');
    });
  });
});
